### PR TITLE
Working method to read new emission parameters. 

### PR DESCRIPTION
**Pull request by rosiealice**

### CODE REVIEW

**Comment by maritsandstad** [comment]
@rosiealice do you want to merge this straight into the "main" feature/fates-fire-emissions branch, or do you want to put it into the fire_emis_calcs branch first and get that working together there before moving it further up the food-chain?

**Comment by rosiealice** [comment]
I think I did both already (merged this into fire_emission_calcs) but this part can go in the 'main' branch now as it is working and might help @mvdebolskiy out with his parameter reading endeavours?

**Comment by rosiealice** [comment]
This is now superceded by the fire_emission_calcs pull request #2

**Comment by rosiealice** [comment]
closing PR on account of duplication

**Pull request closed without merging**
